import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Box sx={{marginBottom: 3, position: "sticky", top: 0, backgroundColor: "white", zIndex: 999}}>
          <Header />
        </Box>
        <Box sx={{backgroundColor: "#f5f5f5"}}>
          {children}
        </Box>
      </body>
    </html>
  );
}
